### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by dohliam** [ehouais/js1k#1]
Hi ehouais, thanks for sharing these great js1k entries! :+1: I notice you haven't included a license. Would it be possible to release them under a free license so that they can be included in the [openjs1k](https://github.com/dohliam/openjs1k) project? Even if you don't plan on using a free license, having a license of some kind would help people know whether or not they can reuse your work. :smile:

**Comment by ehouais** [comment]
Better late than never...
Added license file in commit 62422c6.
